name: Terraform CI

on:
    pull_request:
      branches:
        - main
      paths:
        - 'terraform/**'
        - '.github/workflows/**'

    workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_WORKING_DIR: terraform

jobs:
  terraform-ci:
    name: Terraform CI Checks
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR}}
            
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
                
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.15.6

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: |
        terraform plan \
          -var="environment=dev" \
          -detailed-exitcode \
          -no-color
                   